dist: xenial
language: minimal
env:
    global:
        - IMAGE_NAME=scabbage/idiom-finder-site
script:
  - docker --version
  - env
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME "$IMAGE_NAME:$TRAVIS_BUILD_ID"
  - docker tag $IMAGE_NAME "$IMAGE_NAME:latest"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push $IMAGE_NAME:$TRAVIS_BUILD_ID
  - docker push $IMAGE_NAME:latest